$p = "$env:USERPROFILE\Desktop\AssetManagement\AssetManagement.Web\Views\Asset\FullDetails.cshtml"
$enc = [System.Text.Encoding]::UTF8
$c = [System.IO.File]::ReadAllText($p, $enc)
$old = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("ICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29sLW1kLTMgY29sLTYiPjxkaXYgY2xhc3M9InRleHQtbXV0ZWQgc21hbGwiPtiz2LnYsSDYp9mE2LTYsdin2KE8L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InRleHQtc3VjY2VzcyBmdy1zZW1pYm9sZCI+QChhLlB1cmNoYXNlUHJpY2UuSGFzVmFsdWUgPyAiRUdQICIgKyBhLlB1cmNoYXNlUHJpY2UuVmFsdWUuVG9TdHJpbmcoIk4wIikgOiAi4oCUIik8L2Rpdj48L2Rpdj4="))
$new = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("ICAgICAgICAgICAgQHsKICAgICAgICAgICAgICAgIHZhciBmZExhc3RTYWxlICAgPSBhLlNhbGVSZXF1ZXN0cy5PcmRlckJ5RGVzY2VuZGluZyh4ID0+IHguQ3JlYXRlZEF0KS5GaXJzdE9yRGVmYXVsdCgpOwogICAgICAgICAgICAgICAgdmFyIGZkTGFzdFJlbnRhbCA9IGEuUmVudGFsUmVxdWVzdHMuT3JkZXJCeURlc2NlbmRpbmcoeCA9PiB4LkNyZWF0ZWRBdCkuRmlyc3RPckRlZmF1bHQoKTsKICAgICAgICAgICAgICAgIGRlY2ltYWw/IGZkUHJpY2UgPSBhLlB1cmNoYXNlUHJpY2U7CiAgICAgICAgICAgICAgICBzdHJpbmcgZmRMYWJlbCA9ICJcdTA2MzNcdTA2MzlcdTA2MzEgXHUwNjI3XHUwNjQ0XHUwNjM0XHUwNjMxXHUwNjI3XHUwNjIxIjsKICAgICAgICAgICAgICAgIGlmIChmZExhc3RTYWxlICE9IG51bGwpIHsgZmRQcmljZSA9IGZkTGFzdFNhbGUuT2ZmZXJlZFByaWNlOyBmZExhYmVsID0gIlx1MDYzM1x1MDYzOVx1MDYzMSBcdTA2MjdcdTA2NDRcdTA2MjhcdTA2NGFcdTA2MzkiOyB9CiAgICAgICAgICAgICAgICBlbHNlIGlmIChmZExhc3RSZW50YWwgIT0gbnVsbCkgeyBmZFByaWNlID0gZmRMYXN0UmVudGFsLlByb3Bvc2VkUmVudDsgZmRMYWJlbCA9ICJcdTA2MjdcdTA2NDRcdTA2MjVcdTA2NGFcdTA2MmNcdTA2MjdcdTA2MzEgXHUwNjI3XHUwNjQ0XHUwNjM0XHUwNjQ3XHUwNjMxXHUwNjRhIjsgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbC1tZC0zIGNvbC02Ij48ZGl2IGNsYXNzPSJ0ZXh0LW11dGVkIHNtYWxsIj5AZmRMYWJlbDwvZGl2PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0idGV4dC1zdWNjZXNzIGZ3LXNlbWlib2xkIj5AKGZkUHJpY2UuSGFzVmFsdWUgPyAiRUdQICIgKyBmZFByaWNlLlZhbHVlLlRvU3RyaW5nKCJOMCIpIDogIlx1MjAxNCIpPC9kaXY+PC9kaXY+"))
if ($c.Contains($old)) {
    $c = $c.Replace($old, $new)
    [System.IO.File]::WriteAllText($p, $c, $enc)
    Write-Host "OK: FullDetails price fixed" -ForegroundColor Green
} else {
    Write-Host "WARN: pattern not found exactly" -ForegroundColor Red
}
cd "$env:USERPROFILE\Desktop\AssetManagement"
dotnet build 2>&1 | Select-Object -Last 4
if ($LASTEXITCODE -eq 0) { Write-Host "Build OK!" -ForegroundColor Green }